[tox]
env_list = py312, lint
requires =
    tox-uv==1.36.0
skip_missing_interpreters = true

[testenv]
description = Run the RapidPro test suite
runner = uv-venv-lock-runner
package = skip
set_env =
    DJANGO_SETTINGS_MODULE = temba.settings_ci
commands =
    coverage run manage.py test --keepdb --noinput --verbosity=2 {posargs}
    coverage report -i
    coverage report -i --rcfile .coveragerc_todo
    coverage xml

[testenv:lint]
description = Run pre-commit on all files
runner = uv-venv-lock-runner
package = skip
commands = pre-commit run --all-files
