# Generated by Django 4.2.30 on 2026-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0139_channel_is_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="channelcount",
            new_name="channels_ch_channel_4605f2_idx",
            old_fields=("channel", "count_type", "day"),
        ),
    ]
