# Generated by Django 4.2.30 on 2026-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0175_alter_msg_failed_reason"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemlabelcount",
            new_name="msgs_system_org_id_ee91c9_idx",
            old_fields=("org", "label_type"),
        ),
    ]
