# Generated by Django 4.2.30 on 2026-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0291_flowrun_flows_run_active_or_waiting_has_session"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="flowpathcount",
            new_name="flows_flowp_flow_id_cc1ca5_idx",
            old_fields=("flow", "from_uuid", "to_uuid", "period"),
        ),
        migrations.RenameIndex(
            model_name="flowruncount",
            new_name="flows_flowr_flow_id_58789d_idx",
            old_fields=("flow", "exit_type"),
        ),
    ]
