# Generated by Django 5.2.17 on 2026-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0030_squashed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="adminboundary",
            index=models.Index(fields=["tree_id", "lft"], name="locations_adminboundary_tr0dec"),
        ),
    ]
