from rest_framework.urlpatterns import format_suffix_patterns

from django.urls import path

from .views import (
    ArchivesEndpoint,
    AuthenticateView,
    BoundariesEndpoint,
    BroadcastsEndpoint,
    CampaignEventsEndpoint,
    CampaignsEndpoint,
    ChannelEventsEndpoint,
    ChannelsEndpoint,
    ClassifiersEndpoint,
    ContactActionsEndpoint,
    ContactsEndpoint,
    DefinitionsEndpoint,
    ExplorerView,
    FieldsEndpoint,
    FlowsEndpoint,
    FlowStartsEndpoint,
    GlobalsEndpoint,
    GroupsEndpoint,
    LabelsEndpoint,
    MediaEndpoint,
    MessageActionsEndpoint,
    MessagesEndpoint,
    ResthookEventsEndpoint,
    ResthooksEndpoint,
    ResthookSubscribersEndpoint,
    RootView,
    RunsEndpoint,
    TemplatesEndpoint,
    TicketActionsEndpoint,
    TicketersEndpoint,
    TicketsEndpoint,
    TopicsEndpoint,
    UsersEndpoint,
    WorkspaceEndpoint,
)

urlpatterns = [
    path("", RootView.as_view(), name="api.v2"),
    path("explorer/", ExplorerView.as_view(), name="api.v2.explorer"),
    path("authenticate", AuthenticateView.as_view(), name="api.v2.authenticate"),
    # ========== endpoints A-Z ===========
    path("archives", ArchivesEndpoint.as_view(), name="api.v2.archives"),
    path("boundaries", BoundariesEndpoint.as_view(), name="api.v2.boundaries"),
    path("broadcasts", BroadcastsEndpoint.as_view(), name="api.v2.broadcasts"),
    path("campaigns", CampaignsEndpoint.as_view(), name="api.v2.campaigns"),
    path("campaign_events", CampaignEventsEndpoint.as_view(), name="api.v2.campaign_events"),
    path("channels", ChannelsEndpoint.as_view(), name="api.v2.channels"),
    path("channel_events", ChannelEventsEndpoint.as_view(), name="api.v2.channel_events"),
    path("classifiers", ClassifiersEndpoint.as_view(), name="api.v2.classifiers"),
    path("contacts", ContactsEndpoint.as_view(), name="api.v2.contacts"),
    path("contact_actions", ContactActionsEndpoint.as_view(), name="api.v2.contact_actions"),
    path("definitions", DefinitionsEndpoint.as_view(), name="api.v2.definitions"),
    path("fields", FieldsEndpoint.as_view(), name="api.v2.fields"),
    path("flow_starts", FlowStartsEndpoint.as_view(), name="api.v2.flow_starts"),
    path("flows", FlowsEndpoint.as_view(), name="api.v2.flows"),
    path("globals", GlobalsEndpoint.as_view(), name="api.v2.globals"),
    path("groups", GroupsEndpoint.as_view(), name="api.v2.groups"),
    path("labels", LabelsEndpoint.as_view(), name="api.v2.labels"),
    path("media", MediaEndpoint.as_view(), name="api.v2.media"),
    path("messages", MessagesEndpoint.as_view(), name="api.v2.messages"),
    path("message_actions", MessageActionsEndpoint.as_view(), name="api.v2.message_actions"),
    path("org", WorkspaceEndpoint.as_view(), name="api.v2.org"),  # deprecated
    path("resthooks", ResthooksEndpoint.as_view(), name="api.v2.resthooks"),
    path("resthook_events", ResthookEventsEndpoint.as_view(), name="api.v2.resthook_events"),
    path("resthook_subscribers", ResthookSubscribersEndpoint.as_view(), name="api.v2.resthook_subscribers"),
    path("runs", RunsEndpoint.as_view(), name="api.v2.runs"),
    path("templates", TemplatesEndpoint.as_view(), name="api.v2.templates"),
    path("ticketers", TicketersEndpoint.as_view(), name="api.v2.ticketers"),
    path("tickets", TicketsEndpoint.as_view(), name="api.v2.tickets"),
    path("ticket_actions", TicketActionsEndpoint.as_view(), name="api.v2.ticket_actions"),
    path("topics", TopicsEndpoint.as_view(), name="api.v2.topics"),
    path("users", UsersEndpoint.as_view(), name="api.v2.users"),
    path("workspace", WorkspaceEndpoint.as_view(), name="api.v2.workspace"),
]

urlpatterns = format_suffix_patterns(urlpatterns, allowed=["json", "api"])
