# Generated by Django 4.2.30 on 2026-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0167_alter_contactgroup_is_system"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contacturn",
            name="non_empty_scheme_and_path",
        ),
        migrations.AddConstraint(
            model_name="contacturn",
            constraint=models.CheckConstraint(
                check=models.Q(("scheme", ""), ("path", ""), _connector="OR", _negated=True),
                name="non_empty_scheme_and_path",
            ),
        ),
    ]
