name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    env:
      python-version: "3.12"
      postgis-version: "3.3"
      redis-version: "7.2"
      node-version: "20"
      elastic-version: "7.17.20"
      rpindexer-version: "9.1.9"
      mailroom-version: "9.1.9"
      DJANGO_SETTINGS_MODULE: temba.settings_ci
    strategy:
      matrix:
        pg-version: ["13", "14"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL and PostGIS
        uses: nyaruka/postgis-action@v2.1.0
        with:
          postgresql version: ${{ matrix.pg-version }}
          postgis version: ${{ env.postgis-version }}
          postgresql db: temba
          postgresql user: temba
          postgresql password: temba
          postgresql arguments: "--jit=off"

      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libgdal-dev gettext libmagic1

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Redis
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: ${{ env.redis-version }}

      - name: Install ElasticSearch
        uses: nyaruka/elasticsearch-action@master
        with:
          elastic version: ${{ env.elastic-version }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Initialize environment
        run: |
          uv sync --frozen
          npm install
          sudo npm install -g less
          ln -s ${{ github.workspace }}/temba/settings.py.dev ${{ github.workspace }}/temba/settings.py
          .venv/bin/python manage.py migrate
          # fetch and extract rp-indexer
          wget https://github.com/nyaruka/rp-indexer/releases/download/v${{ env.rpindexer-version }}/rp-indexer_${{ env.rpindexer-version }}_linux_amd64.tar.gz
          tar -xvf rp-indexer_${{ env.rpindexer-version }}_linux_amd64.tar.gz rp-indexer
          # fetch, extract and start mailroom
          wget https://github.com/nyaruka/mailroom/releases/download/v${{ env.mailroom-version }}/mailroom_${{ env.mailroom-version }}_linux_amd64.tar.gz
          tar -xvf mailroom_${{ env.mailroom-version }}_linux_amd64.tar.gz mailroom
          ./mailroom -db=postgres://temba:temba@localhost:5432/temba?sslmode=disable -redis=redis://localhost:6379/10 -log-level=info > mailroom.log &

      - name: Run pre-test checks
        run: |
          # test that everything is well formatted, linted, and has no missing migrations
          .venv/bin/pre-commit run --all-files
          .venv/bin/python manage.py makemigrations --check --dry-run
          # check we can collect and compress all static files
          .venv/bin/python manage.py collectstatic --noinput --verbosity=0
          .venv/bin/python manage.py compress --extension=".haml" --settings=temba.settings_compress

      - name: Run tests
        run: |
          .venv/bin/coverage run manage.py test --keepdb --noinput --verbosity=2
          .venv/bin/coverage report -i
          .venv/bin/coverage report -i --rcfile .coveragerc_todo
          .venv/bin/coverage xml

      - name: Mailroom log
        if: failure()
        run: cat mailroom.log

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
